# Render.com Deployment Configuration
services:
  - type: web
    name: scriptzon
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: LEMON_SQUEEZY_API_KEY
        sync: false
      - key: BASE_URL
        fromService:
          type: web
          name: scriptzon
          envVarKey: RENDER_EXTERNAL_URL
    autoDeploy: true
    plan: free
